server:
  port: 8189
  servlet:
    context-path: /springshop

spring:
  datasource:
    url: jdbc:postgresql://192.168.66.239:5432/springshop?useSSL=false&serverTimezone=UTC
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  thymeleaf:
    cache: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

springshop:
  rabbitmq:
    exchange: spring-shop.exchange
    routing-key: spring.shop
    queue: spring-shop.queue

files:
  storepath:
    icons:  "B:\\myProjects\\SpringShop\\springshopapp\\images\\icons"
    product-images: "B:\\myProjects\\SpringShop\\springshopapp\\images\\product_images"
    review-photos: "B:\\myProjects\\SpringShop\\springshopapp\\images\\review_photos"
    images-dump: "B:\\myProjects\\SpringShop\\springshopapp\\images\\dump"

documents:
  service:
    url: "localhost:10210/documents"