server:
  port: 8189
  servlet:
    context-path: /springshop

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springshop?useSSL=false&serverTimezone=UTC
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  thymeleaf:
    cache: false

files:
  storepath:
    icons:  "B:\\myProjects\\SpringShop\\images\\icons"
    product-images: "B:\\myProjects\\SpringShop\\images\\product_images"
    review-photos: "B:\\myProjects\\SpringShop\\images\\review_photos"
    images-dump: "B:\\myProjects\\SpringShop\\images\\dump"